In [66]:
from const import*
import numpy as np
import random

In [67]:
np.random.seed(10)
lidars = np.random.randint(0, 360, size=360)
lidars

array([265, 125,  15, 320, 123, 156, 221,   8,  73, 256,  40,  16, 356,
       239,  54, 344, 122,  62,  33, 200, 356, 177, 179,  54,  77,  13,
       243, 141, 348, 342, 286, 158,  89, 140, 321,  31, 313, 292, 283,
        18,  93,  77,  94, 248, 156,  74, 216,  15,  18, 118,  71, 344,
       145, 135, 203, 284, 289, 250, 352,  44, 133,   4,  71, 344, 344,
       306, 182, 290, 271, 344, 143, 134, 246,  85, 234, 150,  11, 112,
       268, 220,  62, 185,  79, 232,  42, 237, 313, 235, 353, 306,  45,
       201, 165, 128,  23,   3, 285, 272, 340, 338, 112,  14,  51,  79,
       243, 273, 178,  53, 234, 273, 337, 233,  41,  90, 268, 286, 209,
       144, 128, 159, 357, 201, 244, 254,  22,  96, 322,  67,  95, 355,
        82,  62, 246,  77,  48, 237, 115, 267,  95, 171, 224, 229,  73,
       168, 357, 235, 346,  71, 136, 213, 328, 255,  30, 123, 153, 206,
       213,  13, 169,   4, 215, 350,  28,  39, 347, 103, 265, 263, 150,
        32, 259,   9, 180, 196, 158, 330, 286, 137, 258, 115, 14

In [68]:
bin_lidarsignal = np.linspace(
    0, 360, num=LENGTH_LIDARSIGNAL, endpoint=True)
bin_lidarsignal = np.delete(bin_lidarsignal, 0)
lidars = np.digitize(lidars, bin_lidarsignal)
print(bin_lidarsignal)
lidars


[120. 240. 360.]


array([2, 1, 0, 2, 1, 1, 1, 0, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 1, 2, 1,
       1, 0, 0, 0, 2, 1, 2, 2, 2, 1, 0, 1, 2, 0, 2, 2, 2, 0, 0, 0, 0, 2,
       1, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 2, 2, 2, 2, 0, 1, 0, 0, 2, 2, 2,
       1, 2, 2, 2, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 1, 2, 1,
       2, 2, 0, 1, 1, 1, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 0, 1, 2,
       2, 1, 0, 0, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0,
       2, 0, 0, 1, 0, 2, 0, 1, 1, 1, 0, 1, 2, 1, 2, 0, 1, 1, 2, 2, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 2, 0, 2, 2, 1, 0, 2, 0, 1, 1, 1, 2,
       2, 1, 2, 0, 1, 1, 1, 2, 2, 1, 1, 0, 2, 0, 1, 2, 0, 0, 2, 1, 0, 0,
       1, 0, 1, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1, 2, 2, 1,
       0, 0, 1, 1, 2, 0, 2, 2, 0, 1, 1, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 2,
       0, 1, 2, 1, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 2,
       2, 1, 1, 1, 1, 2, 0, 0, 1, 2, 2, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 0,
       1, 2, 2, 1, 2, 0, 2, 2, 1, 0, 1, 0, 1, 0, 2,

In [69]:
temp_lidars = lidars
bin_lidarspace = np.array([45, 135, 180])
lidars = np.array_split(temp_lidars, bin_lidarspace)
section_lidars_min = [np.amin(lidars[0]), np.amin(
    lidars[1]), np.amin(lidars[2]), np.amin(lidars[3])]
section_lidars_min

[0, 0, 0, 0]

## TH2

In [143]:
import numpy as np
import random
from const import *

np.random.seed(10)

lidars = np.random.randint(130, 999, size=360)
lidars


array([395, 255, 657, 450, 499, 253, 286, 863, 626, 138, 203, 386, 620,
       170, 632, 550, 501, 658, 486, 369, 525, 184, 474, 493, 252, 704,
       675, 330, 998, 819, 821, 184, 207, 583, 143, 885, 539, 512, 783,
       990, 472, 928, 800, 219, 782, 451, 673, 955, 934, 413, 660, 223,
       207, 536, 736, 890, 525, 798, 204, 346, 523, 145, 660, 594, 760,
       201, 474, 525, 787, 560, 265, 845, 926, 931, 598, 892, 994, 602,
       174, 775, 134, 201, 474, 986, 948, 494, 312, 420, 490, 913, 591,
       986, 785, 264, 376, 727, 876, 792, 653, 754, 910, 862, 610, 192,
       632, 315, 721, 494, 362, 684, 879, 443, 877, 995, 948, 687, 843,
       807, 770, 665, 645, 927, 914, 470, 468, 754, 656, 181, 209, 373,
       915, 820, 183, 496, 364, 915, 546, 467, 875, 594, 171, 220, 398,
       628, 416, 339, 531, 274, 258, 801, 487, 331, 886, 510, 552, 896,
       664, 738, 964, 197, 576, 225, 485, 212, 192, 888, 719, 636, 493,
       178, 503, 879, 589, 757, 600, 551, 909, 737, 813, 866, 87

In [144]:
bin_lidarsignal = np.linspace(0, 360, num=LENGTH_LIDARSIGNAL, endpoint=True)
bin_lidarsignal = np.delete(bin_lidarsignal, 0)
lidars_digitized = np.digitize(lidars, bin_lidarsignal)
lidars_digitized


array([3, 2, 3, 3, 3, 2, 2, 3, 3, 1, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 3, 2, 3, 3, 2, 3, 3, 3, 1, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 3, 3, 1, 2, 3, 1, 3, 3, 3, 1,
       3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 1, 3, 3, 3, 3, 2, 3,
       3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3,
       1, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 2, 2, 3, 3, 2, 3, 3,
       3, 3, 3, 3, 3, 1, 3, 1, 3, 1, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3,
       2, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 2, 1, 3, 3, 2, 3, 2, 3, 3, 3,
       3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 1, 3, 3, 1, 2, 3, 3,
       3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 1, 3, 1, 3, 3,
       3, 3, 2, 3, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3,

In [142]:

bin_lidarspace = np.array([45, 135, 180])
lidars_sections = np.array_split(lidars_digitized, bin_lidarspace)
section_lidars_min = [np.amin(section) for section in lidars_sections]
print(section_lidars_min)


[1, 1, 1, 1]


In [145]:
#! chuyen doi state vector
high, low = 1, 0
alpha_space = 0, 2*math.pi
fwVelo_space = -PLAYER_SETTING.MAX_FORWARD_VELO, PLAYER_SETTING.MAX_FORWARD_VELO
rVelo_space = PLAYER_SETTING.MIN_ROTATION_VELO, PLAYER_SETTING.MAX_ROTATION_VELO

lowState = np.array(
    [alpha_space[0], fwVelo_space[0], rVelo_space[0]], dtype=float)
upState = np.array(
    [alpha_space[1], fwVelo_space[1], rVelo_space[1]], dtype=float)

infoState_shape = (ALPHA_SPACE, FWVELO_SPACE, RVELO_SPACE)

bins = []
for i in range(3):
    item = np.linspace(
        lowState[i],
        upState[i],
        num=infoState_shape[i],
        endpoint=False)
    item = np.delete(item, 0)
    bins.append(item)

s = (0.23, 10, -0.4987)
infoStateVector = []
for i in range(3):
    infoStateVector.append(np.digitize(s[i], bins[i]))

infoStateVector = np.array(infoStateVector)
lidarStateVector = np.array(section_lidars_min)


In [146]:
np.concatenate((infoStateVector, lidarStateVector))

array([0, 2, 1, 1, 1, 1, 1], dtype=int64)